# This workflow will perform a test whenever there
# is some change in code done to ensure that the changes
# are not buggy and we are getting the desired output.
name: Build from containerfile
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: "hello-world"

jobs:
  build:
    name: Build image using Buildah
    runs-on: ubuntu-24.04
    steps:

      # Checkout buildah action github repository
      - name: Checkout Buildah action
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          path: "buildah-build"

      - name: Create Dockerfile
        run: |
          cat > Containerfile<<EOF
          FROM busybox
          RUN echo "hello world"
          EOF

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: ./buildah-build/
        with:
          image: ${{ env.IMAGE_NAME }}
          layers: false
          tags: 'latest ${{ github.sha }}'
          containerfiles: |
            ./Containerfile
          extra-args: |
            --pull

      - name: Echo Outputs
        env:
          BUILD_IMAGE: ${{ steps.build_image.outputs.image }}
          BUILD_TAGS: ${{ steps.build_image.outputs.tags }}
          BUILD_IMAGE_WITH_TAG: ${{ steps.build_image.outputs.image-with-tag }}
          BUILD_DIGEST: ${{ steps.build_image.outputs.digest }}
        run: |
          echo "Image: $BUILD_IMAGE"
          echo "Tags: $BUILD_TAGS"
          echo "Tagged Image: $BUILD_IMAGE_WITH_TAG"
          echo "Image Digest: $BUILD_DIGEST"

      # Check if image is build
      - name: Check images created
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: buildah images | grep "$IMAGE_NAME"
